spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///D:\\Harshad\\spring-microservices\\section6\\v2-spring-cloud-config\\external\\config"
        git:
          uri: "https://github.com/PanmandHarshad/spring-microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
