server:
  port: 9191

# Instead of using configuration from yml file you can create a bean for this configuration.
#spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer