spring:
  application:
    name: "eurekaserver"
  config:
    # configserver name should as it is, irrespective of project name.
    # here we have project name also same as configserver
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    logs:
      application:${spring.application.name}